/**
 * Os emojis do "+" das reações, por gaveta, cada um com as palavras que o acham na busca (em
 * português, sem acento). Não é a lista inteira do Unicode: são os que fazem sentido para reagir a
 * uma resenha, num pacote pequeno que vai junto com o site (sem pedir nada à rede).
 */
export interface EmojiEntry {
  e: string;
  /** Palavras da busca, separadas por espaço. */
  k: string;
}

export interface EmojiDrawer {
  id: string;
  label: string;
  /** O emoji que vai na aba da gaveta. */
  icon: string;
  list: readonly EmojiEntry[];
}

const x = (e: string, k: string): EmojiEntry => ({ e, k });

export const EMOJI_DRAWERS: readonly EmojiDrawer[] = [
  {
    id: 'caras',
    label: 'Caras',
    icon: '😀',
    list: [
      x('😀', 'feliz sorriso'),
      x('😄', 'feliz alegre risada'),
      x('😁', 'sorrisao dentes'),
      x('😆', 'risada rindo'),
      x('🤣', 'chorando de rir rolando'),
      x('🙂', 'sorriso leve'),
      x('😉', 'piscadela'),
      x('😊', 'fofo corado feliz'),
      x('😇', 'anjo inocente'),
      x('🥰', 'apaixonado coracoes amor'),
      x('😍', 'olhos de coracao amei apaixonado'),
      x('🤩', 'estrelas fascinado incrivel'),
      x('😘', 'beijo'),
      x('😋', 'gostoso delicia'),
      x('😜', 'brincadeira lingua'),
      x('🤪', 'doido maluco'),
      x('🤓', 'nerd'),
      x('😎', 'oculos escuros estiloso legal'),
      x('🥳', 'festa comemorar'),
      x('😏', 'malicioso sorrisinho'),
      x('😌', 'aliviado tranquilo'),
      x('🤔', 'pensando duvida hmm'),
      x('🤨', 'desconfiado sobrancelha'),
      x('😐', 'neutro sem expressao'),
      x('😑', 'sem expressao tedio'),
      x('🙄', 'revirar olhos'),
      x('😬', 'constrangido careta'),
      x('🤐', 'boca fechada segredo'),
      x('🤫', 'silencio segredo spoiler'),
      x('🫢', 'surpresa mao na boca'),
      x('😮', 'surpresa uau'),
      x('😯', 'espanto'),
      x('😲', 'chocado espantado'),
      x('🤯', 'cabeca explodindo mente explodiu'),
      x('😳', 'envergonhado corado'),
      x('🥺', 'pidao olhos brilhando'),
      x('🥹', 'emocionado segurando lagrimas'),
      x('😢', 'triste chorando lagrima'),
      x('😭', 'chorando muito'),
      x('😱', 'grito medo susto'),
      x('😨', 'medo assustado'),
      x('😰', 'nervoso ansioso'),
      x('😤', 'bufando bravo'),
      x('😠', 'bravo irritado'),
      x('😡', 'furioso raiva'),
      x('🤬', 'xingando palavrao'),
      x('😴', 'sono dormindo tedio'),
      x('🥱', 'bocejo tedio sono'),
      x('🤤', 'babando'),
      x('🤢', 'enjoado nojo'),
      x('🤮', 'vomitando nojo'),
      x('🥴', 'zonzo tonto'),
      x('😵', 'tonto morto'),
      x('😵‍💫', 'tonto confuso espiral'),
      x('🤠', 'cowboy'),
      x('🥸', 'disfarce'),
      x('🫠', 'derretendo'),
      x('🫡', 'continencia respeito'),
      x('🤡', 'palhaco'),
      x('👻', 'fantasma terror'),
      x('💀', 'caveira morri'),
      x('☠️', 'caveira perigo'),
      x('👽', 'alien et'),
      x('🤖', 'robo'),
      x('💩', 'coco ruim'),
      x('😈', 'diabinho malvado'),
    ],
  },
  {
    id: 'gestos',
    label: 'Gestos',
    icon: '👍',
    list: [
      x('👍', 'joinha positivo curti'),
      x('👎', 'negativo nao curti'),
      x('👏', 'palmas aplausos'),
      x('🙌', 'maos para cima viva'),
      x('🙏', 'por favor obrigado reza'),
      x('🤝', 'aperto de mao acordo'),
      x('👌', 'ok perfeito'),
      x('🤌', 'italiano perfeito chef'),
      x('✌️', 'paz vitoria'),
      x('🤞', 'dedos cruzados sorte'),
      x('🤘', 'rock metal'),
      x('🤙', 'liga pra mim'),
      x('👋', 'tchau oi aceno'),
      x('💪', 'forca musculo'),
      x('🫶', 'coracao com as maos amor'),
      x('👀', 'olhos olhando de olho'),
      x('🧠', 'cerebro inteligente'),
      x('🫵', 'voce apontando'),
      x('☝️', 'atencao um'),
      x('🤷', 'sei la tanto faz'),
      x('🤦', 'facepalm vergonha'),
      x('🙈', 'macaco nao vi'),
      x('🙉', 'macaco nao ouvi'),
      x('🙊', 'macaco nao falo'),
    ],
  },
  {
    id: 'coracoes',
    label: 'Corações',
    icon: '❤️',
    list: [
      x('❤️', 'coracao vermelho amor amei'),
      x('🧡', 'coracao laranja'),
      x('💛', 'coracao amarelo'),
      x('💚', 'coracao verde'),
      x('💙', 'coracao azul'),
      x('💜', 'coracao roxo'),
      x('🖤', 'coracao preto'),
      x('🤍', 'coracao branco'),
      x('🤎', 'coracao marrom'),
      x('🩷', 'coracao rosa'),
      x('💔', 'coracao partido triste'),
      x('❤️‍🔥', 'coracao em chamas paixao'),
      x('❤️‍🩹', 'coracao curado'),
      x('💕', 'dois coracoes'),
      x('💖', 'coracao brilhando'),
      x('💘', 'flechada cupido'),
      x('💯', 'cem perfeito'),
      x('✨', 'brilhos magico'),
      x('⭐', 'estrela'),
      x('🌟', 'estrela brilhante'),
      x('💥', 'explosao boom'),
      x('🔥', 'fogo incrivel'),
    ],
  },
  {
    id: 'bichos',
    label: 'Bichos',
    icon: '🐱',
    list: [
      x('🐱', 'gato'),
      x('🐶', 'cachorro'),
      x('🦊', 'raposa'),
      x('🐻', 'urso'),
      x('🐼', 'panda'),
      x('🐸', 'sapo'),
      x('🐵', 'macaco'),
      x('🐧', 'pinguim'),
      x('🦉', 'coruja'),
      x('🦄', 'unicornio'),
      x('🐉', 'dragao'),
      x('🦖', 'dinossauro'),
      x('🐢', 'tartaruga devagar'),
      x('🐌', 'lesma devagar arrastado'),
      x('🐍', 'cobra'),
      x('🦋', 'borboleta'),
      x('🐝', 'abelha'),
      x('🕷️', 'aranha'),
      x('🐙', 'polvo'),
      x('🦈', 'tubarao'),
      x('🌸', 'flor cerejeira'),
      x('🌹', 'rosa flor'),
      x('🌻', 'girassol'),
      x('🍀', 'trevo sorte'),
      x('🌈', 'arco iris'),
      x('🌙', 'lua'),
      x('☀️', 'sol'),
      x('⛈️', 'tempestade'),
      x('❄️', 'neve frio'),
    ],
  },
  {
    id: 'comida',
    label: 'Comida',
    icon: '🍿',
    list: [
      x('🍿', 'pipoca filme'),
      x('🍕', 'pizza'),
      x('🍔', 'hamburguer'),
      x('🍟', 'batata frita'),
      x('🌮', 'taco'),
      x('🍣', 'sushi'),
      x('🍜', 'lamen'),
      x('🍩', 'rosquinha'),
      x('🍰', 'bolo'),
      x('🎂', 'aniversario bolo'),
      x('🍫', 'chocolate'),
      x('🍪', 'biscoito'),
      x('🍓', 'morango'),
      x('🍉', 'melancia'),
      x('🥑', 'abacate'),
      x('🌶️', 'pimenta picante'),
      x('🧀', 'queijo'),
      x('☕', 'cafe'),
      x('🍵', 'cha'),
      x('🍺', 'cerveja'),
      x('🍷', 'vinho'),
      x('🥂', 'brinde'),
      x('🧋', 'bubble tea'),
    ],
  },
  {
    id: 'coisas',
    label: 'Coisas',
    icon: '🎮',
    list: [
      x('🎮', 'videogame controle jogo'),
      x('🕹️', 'fliperama'),
      x('👾', 'invasor jogo'),
      x('🎲', 'dado sorte'),
      x('♟️', 'xadrez estrategia'),
      x('🧩', 'quebra cabeca'),
      x('📚', 'livros leitura'),
      x('📖', 'livro aberto'),
      x('✍️', 'escrevendo'),
      x('🎬', 'cinema filme claquete'),
      x('🎥', 'camera filme'),
      x('📺', 'tv serie'),
      x('🎧', 'fone musica'),
      x('🎵', 'musica nota'),
      x('🎸', 'guitarra rock'),
      x('🎨', 'arte pintura'),
      x('🏆', 'trofeu vitoria campeao'),
      x('🥇', 'medalha ouro primeiro'),
      x('👑', 'coroa rei'),
      x('💎', 'diamante joia'),
      x('🎁', 'presente'),
      x('🎉', 'festa confete'),
      x('🎈', 'balao'),
      x('🚀', 'foguete'),
      x('⚔️', 'espadas luta'),
      x('🛡️', 'escudo'),
      x('🔮', 'bola de cristal magia'),
      x('🪄', 'varinha magica'),
      x('💡', 'ideia lampada'),
      x('⏳', 'ampulheta tempo demorado'),
      x('💤', 'sono zzz'),
      x('💸', 'dinheiro voando caro'),
      x('🗿', 'moai serio'),
    ],
  },
  {
    id: 'sinais',
    label: 'Sinais',
    icon: '✅',
    list: [
      x('✅', 'certo feito check'),
      x('❌', 'errado nao x'),
      x('⭕', 'circulo'),
      x('❗', 'exclamacao importante'),
      x('❓', 'pergunta duvida'),
      x('⁉️', 'o que interrobang'),
      x('‼️', 'exclamacao dupla'),
      x('💢', 'raiva bravo'),
      x('💬', 'balao fala comentario'),
      x('🗯️', 'balao bravo'),
      x('💭', 'pensamento'),
      x('🆗', 'ok'),
      x('🆒', 'cool legal'),
      x('🆕', 'novo'),
      x('🔝', 'top'),
      x('🔁', 'repetir de novo'),
      x('⚠️', 'aviso cuidado'),
      x('🚫', 'proibido'),
      x('♻️', 'reciclar'),
      x('🎯', 'alvo acertou'),
      x('📌', 'tachinha alfinete'),
      x('🇧🇷', 'brasil bandeira'),
      x('🏳️‍🌈', 'arco iris orgulho bandeira'),
    ],
  },
];

/** Busca pelas palavras, sem acento e sem ligar para maiúsculas; vazia, nada. */
export function searchEmoji(query: string, fold: (s: string) => string): EmojiEntry[] {
  const words = fold(query.trim()).split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  for (const d of EMOJI_DRAWERS) {
    for (const item of d.list) {
      if (seen.has(item.e)) continue;
      if (words.every((w) => item.k.split(' ').some((k) => k.startsWith(w)))) {
        seen.add(item.e);
        out.push(item);
      }
    }
  }
  return out;
}
